# Generated by Django 2.1.15 on 2020-04-27 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.Status'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projets', to=settings.AUTH_USER_MODEL),
        ),
    ]
