# Generated by Django 2.1.15 on 2020-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_auto_20200505_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
