# Generated by Django 2.1.15 on 2020-05-12 18:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_auto_20200511_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_percentage',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de parution'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='journal',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modification',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(default=1, help_text='Entre 1 et 10'),
        ),
        migrations.AlterField(
            model_name='task',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Projet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de début'),
        ),
    ]
