# Generated by Django 2.1.15 on 2020-05-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_auto_20200512_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Projet'),
        ),
    ]
